### ISSUE TITLE
Hindsight Experience Replay (HER)

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/JigglypuffRL#15]
As part of [#6](https://github.com/SforAiDl/JigglypuffRL/issues/6)

**Comment by ajaysub110** [comment]
Leaving this for now. Will first implement DDPG since an off-policy algo is required for HER

**Comment by Sharad24** [comment]
Sounds good, Same goes for TD3 I believe.

**Comment by ajaysub110** [comment]
HER uses an off policy algorithm within it because of which replay buffer and network dimensions which are defined within the DDPG class become hard to change from the HER class. I could implement a workaround but it would make things very messy. I think we should keep HER and TD3 on hold until we have revamped the structure of the library. What do you think @Sharad24 ?

**Comment by Sharad24** [comment]
Definitely agree. Have not yet raised a PR for TD3 for the same reason

**Comment by ajaysub110** [comment]
Cool. Makes structuring the repo all the more important!
