### ISSUE TITLE
Basic ActorCritic Policy

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/JigglypuffRL#19]
We should probably have a basic actor-critic policy definition for algorithms that'll be based on it. E.g. #17 (DDPG), A2C, etc

**Comment by ajaysub110** [comment]
Instead of having separate `policies.py` and `values.py` files, we can just have one with `BaseActor`, `BaseCritic` and '`BaseActorCritic` and different policies inheriting from those. Does this match up with what you were planning?
