### ISSUE TITLE
Contextual Bandits

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/JigglypuffRL#42]
Do we want to do add Contextual Bandit algorithms? Especially Deep Contextual Bandits e.g. from [this](https://arxiv.org/pdf/1802.09127.pdf) paper. I couldn't find complete PyTorch implementations of these so I think it might be pretty good to add these.

**Comment by ajaysub110** [comment]
Yeah, contextual bandits will be good. Should we add it to the algo list right now or later on?

**Comment by Sharad24** [comment]
Lets make a checklist here I guess.

**Comment by Sharad24** [comment]
Will reopen this at a future time
