### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/JigglypuffRL#53]
It seems that we're scoring a bit too low on code review as can be seen in the Codacy/Code Review check in the open PRs 

I'd like to request everyone to run pylint as well before pushing/requesting a review on your PR. This prints out messages about your code. Correct these and then push it.

It seems a bit too much to correct all this in one PR but try and not add to the already existing lower quality. As of now, the code scores 5.43/10.0.

**Comment by Sharad24** [comment]
Check all details here: https://app.codacy.com/gh/SforAiDl/JigglypuffRL/files?bid=17409295

**Comment by Zeus3101** [comment]
A lot of them are bad variable names and long statements. I'll correct a few of them if that's okay.

**Comment by Sharad24** [comment]
Yes, please. Thanks!

Especially variables like `s`, etc

**Comment by Zeus3101** [comment]
I had accidentally reformatted on an outdated fork. @ajaysub110 has taken care of the others before I'd noticed. I'll change the variable names soon.
