### ISSUE TITLE
Distributed, Asynchronous Traning, SubprocessVecEnv, Trainer class

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/JigglypuffRL#77]
This is a big issue, so if anyone else is willing to contribute, just comment below

**Comment by Het-Shah** [comment]
I'll do this in parallel with DQN

**Comment by Sharad24** [comment]
Sure

**Comment by Sharad24** [comment]
Also, it would be better to resolve #72 first.

**Comment by Het-Shah** [comment]
Yes, we should start with VectoredEnv and then maybe try to use this with the shared memory concept of the rlpyt library. I'll start with the vectoredEnv implementation.
